###Create Account
POST http://localhost:8080/api/v1/sbbankingapp
Content-Type: application/json

{
  "firstName": "D",
  "lastName": "K",
  "username": "dk",
  "password": "dk",
  "initialBalance": 1000
}

###Get account details using uName
GET http://localhost:8080/api/v1/sbbankingapp?username=bingu

###Get account details using uId
GET http://localhost:8080/api/v1/sbbankingapp/id/13241234

###Update account fields
PATCH http://localhost:8080/api/v1/sbbankingapp/asdfasdf
Content-Type: application/json

{
  "newFirstName": "asdf",
  "newLastName": "asdf",
  "newUsername": "asdf",
  "newPassword": "asdf"
}

###Delete account using uName
DELETE http://localhost:8080/api/v1/sbbankingapp/asdfzxcv

###Delete account using uId
DELETE http://localhost:8080/api/v1/sbbankingapp/deletebyid/zxvasdf415112341234

###Withdrawal transaction
POST http://localhost:8080/api/v1/sbbankingapp/asdfasdf/transactions
Content-Type: application/json

{
  "type": "withdrawal",
  "amount": 1000
}

###Get account balance
GET http://localhost:8080/api/v1/sbbankingapp/bingu/balance

###Deposit transaction
POST http://localhost:8080/api/v1/sbbankingapp/asdfasdf/transactions
Content-Type: application/json

{
  "type": "deposit",
  "amount": 2000
}
