###Create Account
POST http://localhost:8080/api/v1/accounts
Content-Type: application/json

{
  "firstName": "D",
  "lastName": "K",
  "username": "dk",
  "password": "dk",
  "initialBalance": 1000
}

###Get account details using uName
GET http://localhost:8080/api/v1/accounts?username=bingu

###Get account details using uId
GET http://localhost:8080/api/v1/accounts/1b2f87da-5881-43ce-8280-d55cb1227d39

###Update account fields using uName
PATCH http://localhost:8080/api/v1/accounts?username=asdfasdf
Content-Type: application/json

{
  "newFirstName": "asdf",
  "newLastName": "asdf",
  "newUsername": "asdf",
  "newPassword": "asdf"
}

###Update account fields using uId
PATCH http://localhost:8080/api/v1/accounts/1b2f87da-5881-43ce-8280-d55cb1227d39
Content-Type: application/json

{
  "newFirstName": "zxcv",
  "newLastName": "zxcv",
  "newUsername": "zxcv",
  "newPassword": "zxcv"
}

###Delete account using uName
DELETE http://localhost:8080/api/v1/accounts?username=zxcv

###Delete account using uId
DELETE http://localhost:8080/api/v1/accounts/f75f605e-bcdf-430e-9a9d-b2172d3a2daa

###Get account balance using uName
GET http://localhost:8080/api/v1/accounts/balance?username=bingu

###Get account balance using uId
GET http://localhost:8080/api/v1/accounts/8e71e605-9aea-43e5-b432-b72a1be05842/balance

###Withdrawal transaction using uName
POST http://localhost:8080/api/v1/accounts/transactions?username=dk
Content-Type: application/json

{
  "type": "WITHDRAWAL",
  "amount": 500
}

###Withdrawal transaction using uId
POST http://localhost:8080/api/v1/accounts/e86264e0-295b-46fc-a7ef-5995efa1a015/transactions
Content-Type: application/json

{
  "type": "WITHDRAWAL",
  "amount": 100
}

###Deposit transaction using uName
POST http://localhost:8080/api/v1/accounts/transactions?username=dk
Content-Type: application/json

{
  "type": "DEPOSIT",
  "amount": 600
}

###Deposit transaction using uId
POST http://localhost:8080/api/v1/accounts/8e71e605-9aea-43e5-b432-b72a1be05842/transactions
Content-Type: application/json

{
  "type": "DEPOSIT",
  "amount": 2000000
}