package com.cfkiatong.springbootbankingapp.service;

import com.cfkiatong.springbootbankingapp.dto.Mapper;
import com.cfkiatong.springbootbankingapp.dto.Role;
import com.cfkiatong.springbootbankingapp.dto.request.ChangeAccountOwnerRequest;
import com.cfkiatong.springbootbankingapp.dto.response.AccountResponse;
import com.cfkiatong.springbootbankingapp.entity.Account;
import com.cfkiatong.springbootbankingapp.entity.UserEntity;
import com.cfkiatong.springbootbankingapp.exception.ForbiddenException;
import com.cfkiatong.springbootbankingapp.exception.business.AccountNotFoundException;
import com.cfkiatong.springbootbankingapp.exception.business.InvalidAccountStateException;
import com.cfkiatong.springbootbankingapp.exception.business.UserNotFoundException;
import com.cfkiatong.springbootbankingapp.repository.AccountRepository;
import com.cfkiatong.springbootbankingapp.repository.UserEntityRepository;
import com.cfkiatong.springbootbankingapp.services.AccountService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AccountServiceTest {

    @Mock
    private UserEntityRepository userEntityRepository;
    @Mock
    private AccountRepository accountRepository;

    private AccountService accountService;

    private UserEntity userEntity;
    private Account account;

    private final UUID ownerId = UUID.randomUUID();
    private final UUID accountId = UUID.randomUUID();

    private final BigDecimal balance = new BigDecimal("10000");

    @BeforeEach
    void setup() {
        Mapper mapper = new Mapper();
        accountService = new AccountService(
                accountRepository,
                userEntityRepository,
                mapper
        );

        //ARRANGE
        userEntity = new UserEntity(
                "firstName",
                "lastName",
                "email",
                "owner",
                "password",
                new HashSet<>(Set.of(Role.ADMIN, Role.USER)),
                null
        );
        userEntity.setUserId(ownerId);

        account = new Account();
        account.setId(accountId);
        account.setAccountOwner(userEntity);
        account.setBalance(balance);
    }

    //ACCOUNT SERVICE TESTS

    @Test
    void getAccount_validOwner_returnAccountResponse() {
        AccountResponse expectedResponse = new AccountResponse(accountId, "owner", balance);

        when(accountRepository.findById(accountId))
                .thenReturn(Optional.of(account));

        AccountResponse result = accountService.getAccount(ownerId, accountId);

        assertEquals(expectedResponse, result);
    }

    //NOTE: No accountId check since accountId generated by JPA
    @Test
    void createAccount_validOwner_returnAccountResponse() {
        when(userEntityRepository.findById(ownerId))
                .thenReturn(Optional.of(userEntity));

        AccountResponse result = accountService.createAccount(ownerId);

        ArgumentCaptor<Account> captor = ArgumentCaptor.forClass(Account.class);

        verify(accountRepository).save(captor.capture());

        Account savedAccount = captor.getValue();

        assertEquals(userEntity, savedAccount.getAccountOwner());
        assertEquals(BigDecimal.ZERO, savedAccount.getBalance());

        assertEquals("owner", result.accountOwner());
        assertEquals(BigDecimal.ZERO, result.balance());
    }

    @Test
    void changeAccountOwner_validRequest_updateAccountOwner() {
        UserEntity newOwner = new UserEntity();
        newOwner.setUsername("newOwner");

        ChangeAccountOwnerRequest request = new ChangeAccountOwnerRequest("newOwner");

        AccountResponse expectedResponse = new AccountResponse(accountId, "newOwner", balance);
        when(userEntityRepository.findByUsername("newOwner")).thenReturn(Optional.of(newOwner));
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        AccountResponse result = accountService.changeAccountOwner(ownerId, accountId, request);

        assertEquals(newOwner, account.getAccountOwner());
        assertEquals(expectedResponse, result);
    }


    @Test
    void deleteAccount_validOwner_deleteAccount() {
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        accountService.deleteAccount(ownerId, accountId);

        verify(accountRepository).deleteById(accountId);
    }

    //EXCEPTION TESTS

    @Test
    void findAndValidateAccount_nonexistentAccount_throwAccountNotFoundException() {
        when(accountRepository.findById(accountId)).thenReturn(Optional.empty());

        assertThrows(AccountNotFoundException.class, () -> accountService.getAccount(ownerId, accountId));
    }

    @Test
    void findAndValidateAccount_invalidOwner_throwForbiddenException() {
        UUID wrongOwnerId = UUID.randomUUID();
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        assertThrows(ForbiddenException.class, () -> accountService.getAccount(wrongOwnerId, accountId));
    }

    @Test
    void changeAccountOwner_newAccountOwnerUserNotFound_throwUserNotFoundException() {
        ChangeAccountOwnerRequest changeAccountOwnerRequest = new ChangeAccountOwnerRequest("newOwner");

        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));
        when(userEntityRepository.findByUsername(changeAccountOwnerRequest.newAccountOwner())).thenReturn(Optional.empty());

        assertThrows(UserNotFoundException.class, () -> accountService.changeAccountOwner(ownerId, accountId, changeAccountOwnerRequest));
    }

    @Test
    void changeAccountOwner_newUserEqualsCurrentUser_throwInvalidAccountStateException() {
        ChangeAccountOwnerRequest changeAccountOwnerRequest = new ChangeAccountOwnerRequest("owner");

        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));
        when(userEntityRepository.findByUsername(changeAccountOwnerRequest.newAccountOwner())).thenReturn(Optional.of(userEntity));

        assertThrows(InvalidAccountStateException.class, () -> accountService.changeAccountOwner(ownerId, accountId, changeAccountOwnerRequest));
    }

}