package com.cfkiatong.springbootbankingapp.service;

import com.cfkiatong.springbootbankingapp.dto.Mapper;
import com.cfkiatong.springbootbankingapp.dto.request.ChangeAccountOwnerRequest;
import com.cfkiatong.springbootbankingapp.dto.response.AccountResponse;
import com.cfkiatong.springbootbankingapp.entity.Account;
import com.cfkiatong.springbootbankingapp.entity.UserEntity;
import com.cfkiatong.springbootbankingapp.repository.AccountRepository;
import com.cfkiatong.springbootbankingapp.repository.UserEntityRepository;
import com.cfkiatong.springbootbankingapp.services.AccountService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;


import java.math.BigDecimal;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AccountServiceTest {

    @Mock
    private UserEntityRepository userEntityRepository;
    @Mock
    private AccountRepository accountRepository;

    private Mapper mapper;
    private AccountService accountService;

    private UUID ownerId;
    private String ownerUsername;
    private UUID accountId;
    private UserEntity userEntity;
    private Account account;
    private final BigDecimal balance = new BigDecimal("10000");
    private final BigDecimal zeroBalance = new BigDecimal("0");

    @BeforeEach
    void setup() {
        mapper = new Mapper();
        accountService = new AccountService(
                accountRepository,
                userEntityRepository,
                mapper
        );

        //ARRANGE
        ownerId = UUID.randomUUID();
        ownerUsername = "owner";
        userEntity = new UserEntity();
        userEntity.setUserId(ownerId);
        userEntity.setUsername(ownerUsername);

        account = new Account();
        accountId = UUID.randomUUID();
        account.setId(accountId);
        account.setAccountOwner(userEntity);
        account.setBalance(balance);
    }

    @Test
    void getAccount_validOwner_returnAccountResponse() {
        AccountResponse expectedResponse = new AccountResponse(accountId, ownerUsername, balance);

        when(accountRepository.findById(accountId))
                .thenReturn(Optional.of(account));

        AccountResponse result = accountService.getAccount(ownerId, accountId);

        assertEquals(expectedResponse, result);
    }

    //NOTE: No accountId check since accountId generated by JPA
    @Test
    void createAccount_validOwner_returnAccountResponse() {
        when(userEntityRepository.findById(ownerId))
                .thenReturn(Optional.of(userEntity));

        AccountResponse result = accountService.createAccount(ownerId);

        ArgumentCaptor<Account> captor = ArgumentCaptor.forClass(Account.class);

        verify(accountRepository).save(captor.capture());

        Account savedAccount = captor.getValue();

        assertEquals(userEntity, savedAccount.getAccountOwner());
        assertEquals(BigDecimal.ZERO, savedAccount.getBalance());

        assertEquals(ownerUsername, result.accountOwner());
        assertEquals(BigDecimal.ZERO, result.balance());
    }

    @Test
    void changeAccountOwner_validRequest_updateAccountOwner() {
        //Arrange
        UserEntity newOwner = new UserEntity();
        newOwner.setUsername("newOwner");

        ChangeAccountOwnerRequest request = new ChangeAccountOwnerRequest();
        request.setNewAccountOwner("newOwner");

        AccountResponse expectedResponse = new AccountResponse(accountId, "newOwner", balance);
        when(userEntityRepository.findByUsername("newOwner")).thenReturn(Optional.of(newOwner));
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        //Act
        AccountResponse result = accountService.changeAccountOwner(ownerId, accountId, request);

        //Assert & Verify
        assertEquals(newOwner, account.getAccountOwner());
        assertEquals(expectedResponse, result);
    }


    @Test
    void shouldDeleteAccountFromRepository() {
        when(accountRepository.findById(accountId)).thenReturn(Optional.of(account));

        accountService.deleteAccount(ownerId, accountId);

        verify(accountRepository).deleteById(accountId);
    }

}
